### PR TITLE
Make the contact page map as a parallax background

### LINKED ISSUE #369: Make the contact page map as parallax background
**Is your feature request related to a problem? Please describe.**
Currently it is like normal background.

**Describe the solution you'd like**
Make the contact page map as parallax background.

**Are you working on it?**
Yes

### PR DESCRIPTION
**Pull request by YoshithaRathnayake**
## Purpose

The purpose of this PR is to fix #369

## Goals

Making the contact page map as a parallax background

## Approach

I made the contact page map as parallax background.

### Preview Link
https://yoshitharathnayake.github.io/sack-site/contact_us

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kumuditha-udayanga** [comment]
@YoshithaRathnayake preview link isn't working

**Comment by YoshithaRathnayake** [comment]
@kumuditha-udayanga is it ok now that is because I changed my username after creating this pr so in this pr there was the old username and I added the new username to that.

**Comment by Piumal1999** [comment]
https://github.com/acf-sack/sack-site/issues/369#issuecomment-1016344200
> I think that the parallax effect doesn't go well with maps. Even on the https://demos.creative-tim.com/material-kit-pro-bs4/examples/contact-us.html example page, they haven't used the parallax effect

.. because it hides the map controls when scrolling. However, it is totally fine if the map is just a static image (But then we will not have any advantage of displaying the map). WDYT? @kumuditha-udayanga 

https://user-images.githubusercontent.com/27498587/151489634-3787b514-400d-4921-a6d5-2a96c3bc5161.mov

**Comment by Piumal1999** [comment]
Closing this issue since this feature is no longer required

**Pull request closed without merging**
