### PR TITLE
added a class to the phone number

### PR DESCRIPTION
**Pull request by tharuka01**
so its easy to add css

### CODE REVIEW

**Comment by Yoshitha-SACK** [comment]
Don't make pr to a one thing

**Comment by Yoshitha-SACK** [comment]
If you can close all PRs and make a one pr

**Comment by jayasanka-sack** [comment]
Yes, I agree with @Yoshitha-SACK ! 

Could you please update the previous PR with this change?

**Comment by jayasanka-sack** [comment]
Also, the issue is to change the phone number in the navigation bar. 

The correct CSS would be:
```css
.btn-contact a {
    color: #00316A;
}
```
image

to the following:
image

**Comment by Yoshitha-SACK** [comment]
> Also, the issue is to change the phone number in the navigation bar.
> 
> The correct CSS would be:
> 
> ```css
> .btn-contact a {
>     color: #00316A;
> }
> ```
> 
> image
> 
> to the following: image

Yeah

**Comment by Piumal1999** [comment]
Hi @tharuka01, from next time onwards please put a comment on the issue before start working on it. So wen can assign you to the issue. And fill the pull request description according to the given template. 
Example: https://github.com/acf-sack/sack-site/pull/305

**Comment by tharuka01** [comment]
> If you can close this or all PRs and make a one pr for all things

ah ok

**Pull request closed without merging**
