### PR TITLE
Remove the horizontal scroll bar

### LINKED ISSUE #328: Remove the Home page horizontal scroll bar
**Describe the bug**
An unwanted side scroll bar has merged in the sack-site.

**To Reproduce**
1. Go to '[www.sack.edu.lk](https://www.sack.edu.lk/)'
2. See error

**Expected behavior**
Remove the Home page side scroll bar.

**Screenshots**
Screenshot (16)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: 97.0.1072.55

**Are you working on it?**
Yes

### PR DESCRIPTION
**Pull request by Yoshitha-SACK**
## Purpose

The purpose of this PR is to fix #328

## Goals

Removing the Horizontal Scroll Bar in Home Page.

## Approach

I removed the unwanted classes in index.html file.

### Preview Link
https://yoshitha-sack.github.io/sack-site/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Related PRs
 
#330

### CODE REVIEW

**Comment by Piumal1999** [comment]
Good job! @Yoshitha-SACK 

Could you please update the issue number? It should be 328. Also, add the previous pull request number (the one you accidentally closed) to the Related PRs section.

**Comment by Yoshitha-SACK** [comment]
Ok

**Comment by Yoshitha-SACK** [comment]
@Piumal1999 Now is it ok

**Review by Piumal1999 — APPROVED** [review]
Looks good! Thank you @Yoshitha-SACK

**Pull request merged**
