### PR TITLE
Add ACF Link to the Navbar

### LINKED ISSUE #352: Link the ACF Page to the Navbar.
**Is your feature request related to a problem? Please describe.**
Currently the acf page is not linked to the navbar.

**Describe the solution you'd like**
Link the acf page to the navbar.

**Screenshots
image

**Are you working on it?**
Yes

### PR DESCRIPTION
**Pull request by YoshithaRathnayake**
## Purpose

The purpose of this PR is to fix #352

## Goals

Adding the ACF link to the navbar.

## Approach

I added the acf link to the navbar.

### Screenshots

image

  
### Preview Link
https://yoshitha-sack.github.io/sack-site/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by jayasanka-sack** [comment]
This should come under a new menu named `Societies`. 

And it should be `Computer Fraternity` not `ACF`

**Review by jayasanka-sack — CHANGES_REQUESTED** [review]
This should come under a new menu named `Societies`.

And it should be `Computer Fraternity` not `ACF`

**Comment by Yoshitha-SACK** [comment]
So I should make a dropdown right ?

**Comment by Piumal1999** [comment]
> So I should make a dropdown right ?

Yeah @Yoshitha-SACK

**Pull request closed without merging**
