### PR TITLE
Remove the  A/L Application

### LINKED ISSUE #372: Remove 2023 A/L Application form
**Is your feature request related to a problem? Please describe.**
- In the Quick Access section on the home page, the A/L application form should be removed because the deadline has passed.
**Describe the solution you'd like**
- Remove the A/L application form from the Quick Access section.

### PR DESCRIPTION
**Pull request by VishwaAmarasinghe**
## Purpose

The purpose of this PR is to fix #372

## Goals

Remove  A/L Application from the home page

## Approach

I remove the divs that were made for the A/L Application in index.html

### Screenshots
image

  
### Preview Link
https://vishwaamarasinghe.github.io/sack-site/
##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by Piumal1999 — APPROVED** [review]
Looks good to me. 
@kumuditha-udayanga do we have to remove the application pdf also?

**Comment by kumuditha-udayanga** [comment]
Let's remove the application file as well, @VishwaAmarasinghe.

**Review by kumuditha-udayanga — CHANGES_REQUESTED** [review]
Thank you for getting this done. Let's remove the application file too, @VishwaAmarasinghe

**Comment by VishwaAmarasinghe** [comment]
> Thank you for getting this done. Let's remove the application file too, @VishwaAmarasinghe

Ok brother

**Comment by VishwaAmarasinghe** [comment]
OK I remove the AL application pdf .

**Review by kumuditha-udayanga — APPROVED** [review]
Thank you @VishwaAmarasinghe!

**Pull request merged**
