### PR TITLE
Remove global css from custom.css file

### LINKED ISSUE #340: Remove custom CSS that effects globally
**Is your feature request related to a problem? Please describe.**
There are some custom CSS classes that affect the whole elements such as headings, paragraphs. 
Please remove them from the custom.css file. 

ex: 

```css
 body h3, body h4, body h5 {
  font-family: Lato, sans-serif;
  color: #2e8df3;
  font-weight: 700;
}
```

This is wrong. We should not select elements unless there's a specific reason. 

**Are you working on it?**
No

### PR DESCRIPTION
**Pull request by Yoshitha-SACK**
## Purpose

The purpose of this PR is to fix #340

## Goals

Removing global css from custom.css file.

## Approach

I removed the unwanted global css from custom.css file.

## Preview Link
https://yoshitha-sack.github.io/sack-site/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by Yoshitha-SACK** [comment]
@Piumal1999 , @jayasanka-sack , @kumuditha-udayanga , @sathsarabandaraj

**Comment by Yoshitha-SACK** [comment]
@kumuditha-udayanga

**Review by Piumal1999 — CHANGES_REQUESTED** [review]
Good job @Yoshitha-SACK 
After removing these, the contact page heading styles are changed. Please have a look and fix those styles.

**Comment by Yoshitha-SACK** [comment]
Ok @Piumal1999

**Review by jayasanka-sack — COMMENTED** [review]
Thanks for getting this done @Yoshitha-SACK !


@Piumal1999 I don't think the contact us page's main heading. However, it affects other titles in the same page by removing that weird light blue color. Therefore, this looks good to me.

But I'm wondering why those headings are so bold. It's different than in the [material kit](https://demos.creative-tim.com/material-kit-bs4/#typography).

It seems someone has changed the `_text.scss` file. @Yoshitha-SACK Can you look into that?

**Review by jayasanka-sack — APPROVED** [review]
> But I'm wondering why those headings are so bold. It's different than in the material kit.

> It seems someone has changed the _text.scss file. @Yoshitha-SACK Can you look into that?

I found the issue. It's not because of the _text.scss file. Someone has added `font-weight-bold` for subtitles in the contact us page. Those should be removed in a separate PR. Therefore approving this PR! Thansk @Yoshitha-SACK !

**Comment by Yoshitha-SACK** [comment]
> > But I'm wondering why those headings are so bold. It's different than in the material kit.
> 
> > It seems someone has changed the _text.scss file. @Yoshitha-SACK Can you look into that?
> 
> I found the issue. It's not because of the _text.scss file. Someone has added `font-weight-bold` for subtitles in the contact us page. Those should be removed in a separate PR. Therefore approving this PR! Thansk @Yoshitha-SACK !

Ok @jayasanka-sack shall I make a new issue for that bold case

**Comment by Yoshitha-SACK** [comment]
> > But I'm wondering why those headings are so bold. It's different than in the material kit.
> 
> > It seems someone has changed the _text.scss file. @Yoshitha-SACK Can you look into that?
> 
> I found the issue. It's not because of the _text.scss file. Someone has added `font-weight-bold` for subtitles in the contact us page. Those should be removed in a separate PR. Therefore approving this PR! Thansk @Yoshitha-SACK !

So @jayasanka-sack is it ok to keep the headings in black color or should I add a blue color

**Comment by Piumal1999** [comment]
> Someone has added `font-weight-bold` for subtitles in the contact us page. Those should be removed in a separate PR.
Yeah, that's right.

> is it ok to keep the headings in black color or should I add a blue color
I think black colour will be good

**Review by Piumal1999 — APPROVED** [review]
Thank you @Yoshitha-SACK

**Pull request merged**
