### PR TITLE
Add links to contact page phone numbers

### LINKED ISSUE #367: Add a link to the phone numbers in contact page
**Is your feature request related to a problem? Please describe.**
There is not link to the phone number in contact page.

**Describe the solution you'd like**
Add a link to the phone numbers in contact page.

**Are you working on it?**
Yes

### PR DESCRIPTION
**Pull request by Yoshitha-SACK**
## Purpose

The purpose of this PR is to fix #367 

## Goals

Adding links to the contact page phone numbers.

## Approach

I add a href attribute and add the necessary links.

### Screenshots

image

  
### Preview Link
https://yoshitha-sack.github.io/sack-site/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by Yoshitha-SACK** [comment]
@Piumal1999 the preview will not be available because the preview link branch is nav-logo.

**Comment by kumuditha-udayanga** [comment]
Thank you @Yoshitha-SACK, looks good for me

**Review by kumuditha-udayanga — DISMISSED** [review]

**Comment by Piumal1999** [comment]
@Yoshitha-SACK  Shall we add the anchor tag only for the phone numbers? The **Tel:** part should not be changed.

**Comment by Yoshitha-SACK** [comment]
Ah ok

**Comment by Yoshitha-SACK** [comment]
now is it ok @kumuditha-udayanga

**Comment by akeel230** [comment]
@Yoshitha-SACK I think you have added tel: part twice. @Piumal1999

**Comment by kumuditha-udayanga** [comment]
@akeel230 that's because one Tel: displays in the page as a text and the other Tel is required to the `a` tag.

**Comment by Yoshitha-SACK** [comment]
> @akeel230 that's because one Tel: displays in the page as a text and the other Tel is required to the `a` tag.

Yes ayya so is it good @kumuditha-udayanga

**Comment by Piumal1999** [comment]
Good job @Yoshitha-SACK . Can you please update the screenshot before merging this pr?

**Review by kumuditha-udayanga — APPROVED** [review]
Good work! @Yoshitha-SACK

**Review by Piumal1999 — APPROVED** [review]
Good job @Yoshitha-SACK Thank you

**Pull request merged**
