### PR TITLE
Change the primary colour of material kit css

### LINKED ISSUE #309: Change the primary colour of material kit css
**Is your feature request related to a problem? Please describe.**
The primary colour of material kit is purple. But we don't need to use purple as our primary colour. (ex: on links, tabs, buttons, etc)

**Describe the solution you'd like**
The primary colour should be the colour of `text-info`. See the [components](https://demos.creative-tim.com/material-kit-bs4/index?_ga=2.158042362.1967954257.1641402362-149862726.1641402362) page. Please recompile the `material-kit.css` and relevant files to change the colour.  Use scss to recompile.

Please follow the following documentation:
https://demos.creative-tim.com/material-kit/docs/2.1/getting-started/build-tools.html

**Are you working on it?**
No

### PR DESCRIPTION
**Pull request by Yoshitha-SACK**
## Purpose

The purpose of this PR is to fix #309

## Goals

Changing the primary colour of material kit css.

## Approach

I changed the primary colour to cyan-500

### Preview Link
https://yoshitha-sack.github.io/sack-site/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by sathsarabandaraj — CHANGES_REQUESTED** [review]
Don't edit material-kit css files
Create custom css for changes

**Review by sathsarabandaraj — APPROVED** [review]
Thank you @Yoshitha-SACK

**Comment by Piumal1999** [comment]
Don't we have to rebuild the css files after changing the primary colour? If yes, we'll have to reopen the issue. @jayasanka-sack @sathsarabandaraj

**Comment by jayasanka-sack** [comment]
Yes, we should revert it. But unfortunately, we can't revert it because @Yoshitha-SACK has opened another PR with the same branch.

**Pull request merged**
