### PR TITLE
Update the new committee members in the ACF Page

### LINKED ISSUE #447: Update the names of the new committee members for the year 2023
**Is your feature request related to a problem? Please describe.**
Currently, in the ACF page there is old committee (for the year 2022) members' names

**Describe the solution you'd like**
Update the names of the new committee members for the year 2023

**Are you working on it?**
Yes

### PR DESCRIPTION
**Pull request by YoshithaRathnayake**
## Purpose

The purpose of this PR is to fix #447 

## Goals

Updating the new committee members in the ACF Page

## Approach

I updated the new committee members in the ACF Page

### Preview Link

https://pr-450-sack-site-acf.surge.sh/acf

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by YoshithaRathnayake** [comment]
@sathsarabandaraj can you review this PR?

**Comment by YoshithaRathnayake** [comment]
@Hasthikagirihagama can you review this?

**Review by Hasthikagirihagama — APPROVED** [review]
Thank you ! @YoshithaRathnayake

**Comment by YoshithaRathnayake** [comment]
> Thank you ! @YoshithaRathnayake

Your Welcome @Hasthikagirihagama!

**Pull request merged**
