### PR TITLE
Make the bugs in acf page

### LINKED ISSUE #357: Search icon on ACF page mobile view is not working
**Describe the bug**
In the ACF page desktop view, we don't have a search option. But in the mobile view, we can see a search icon on navbar, and its not working.

**To Reproduce**
1. Go to 'acf.sack.edu.lk'
2. Go to mobile view (using developer tools)
3. See error

**Expected behavior**
We should reuse the main navbar for the ACF page.
Add the main navbar to the acf page.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Any
 - OS: [e.g. iOS8.1] Any
 - Browser [e.g. stock browser, safari] Any

**Additional context**
N/A

**Are you working on it?**
No

### PR DESCRIPTION
**Pull request by Yoshitha-SACK**
## Purpose

The purpose of this PR is to fix #357

## Goals

Making the bugs in acf page.

## Approach

I do the things in the issue.

### Screenshots

image

### Preview Link
https://yoshitha-sack.github.io/sack-site/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by Yoshitha-SACK** [comment]
@Piumal1999 , @jayasanka-sack , @kumuditha-udayanga , @sathsarabandaraj

**Review by kumuditha-udayanga — CHANGES_REQUESTED** [review]
Good work @Yoshitha-SACK, could you format the code lines which you added, the `<script>` tags

**Comment by Yoshitha-SACK** [comment]
Done formatted @kumuditha-udayanga

**Comment by Yoshitha-SACK** [comment]
Should I add a extra line to the bottom

**Comment by kumuditha-udayanga** [comment]
Yes @Yoshitha-SACK

**Comment by Yoshitha-SACK** [comment]
Done @kumuditha-udayanga

**Review by kumuditha-udayanga — APPROVED** [review]
Well done! @Yoshitha-SACK, Keep it up.

**Pull request merged**
