### PR TITLE
font change to Roboto of history page

### PR DESCRIPTION
**Pull request by killerkc12**
## Purpose
On the history page there was different number of fonts
https://github.com/acf-sack/sack-site/issues/256

The purpose of this PR is to fix #256

## Goals
All the font change to the Roboto Family.

## Approach
Added the font family as the "Roboto".

### Screenshots
image
  
### Preview Link
https://killerkc12.github.io/sack-site/history/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Related PRs
#254 

## Test environment
OS : Windows
Browser : Google Chrome
 

## Learning
Learn about the new font-family.

### CODE REVIEW

**Comment by killerkc12** [comment]
> @killerkc12, Thank you for getting this done, can you provide a preview link(using surge or GitHub pages) and also fill the PR template.

yes definitely

**Comment by kumuditha-udayanga** [comment]
@killerkc12, Since this is a new branch we forgot to add the PR template, Sorry about that. I've added the template to your PR, now you can fill it.

**Comment by killerkc12** [comment]
to publish on surge I need to change the CNAME or not, because it showing that I don't have permission to publish on it

**Comment by kumuditha-udayanga** [comment]
> to publish on surge I need to change the CNAME or not, because it showing that I don't have permission to publish on it
No, you don't want to change the CNAME.

**Comment by killerkc12** [comment]
> > to publish on surge I need to change the CNAME or not, because it showing that I don't have permission to publish on it
> > No, you don't want to change the CNAME.

I'm unable to deploy it showing don't have permission
what should I do

**Comment by killerkc12** [comment]
> You can use GitHub pages,
> 
> 1. Go to the forked repo 'killerkc12/sack-site'
> 2. Then go to 'settings' and go to the 'Pages' option in the sidebar
> 3. There you will find a section named 'Source', select the branch which you use to send the PR and click on save.

I did it already -> https://killerkc12.github.io/sack-site/
but this is not working for history page because of base_url

**Comment by kumuditha-udayanga** [comment]
https://killerkc12.github.io/sack-site/history/ This works

**Comment by killerkc12** [comment]
done

**Comment by kumuditha-udayanga** [comment]
Can you change the font of the header title to Roboto too.

**Comment by killerkc12** [comment]
> Can you change the font of the header title to Roboto too? Don't commit the Gemfile and Gemfile. lock files

ok

**Comment by kumuditha-udayanga** [comment]
@killerkc12, Don't include the changes or delete the gemfile and gemfile.lock files

**Comment by killerkc12** [comment]
> @killerkc12, Don't include the changes or delete the gemfile and gemfile.lock files

those files removed already

**Pull request closed without merging**
