### PR TITLE
Wrong college email

### LINKED ISSUE #20: Wrong college email
**Describe the bug**
The current email in the top of the page is wrong

**To Reproduce**
Replace "sacollegekdy@sltnet.lk" from "sackandy@sltnet.lk"

**Expected behavior**
"sackandy@sltnet.lk"

Screenshot 2020-03-11 at 23 16 41

# Current Behavior
Screenshot 2020-03-11 at 22 55 08

### PR DESCRIPTION
**Pull request by ValanceThomas5**
-Wrong college email
-The purpose of this PR is to fix #20 
email

### CODE REVIEW

**Comment by kumuditha-udayanga** [comment]
The issue is already been fixed

**Comment by kumuditha-udayanga** [comment]
I'll remove my PR

**Comment by kumuditha-udayanga** [comment]
Malli not only in home page in every page the email is wrong correct them all

**Comment by jayasanka-sack** [comment]
@ValanceThomas5  refer to this: https://github.com/acf-sack/sack-site/pull/21

**Pull request closed without merging**
