### PR TITLE
Improve the quality of the St. Anthony's College logo

### LINKED ISSUE #56: Improve the quality of the logo
**Describe the bug**
The current image is in a very low quality

**To Reproduce**
1. Create a new image using designing software.
2. Make it to the correct size 160 x 26
3. Replace the current image with it.

**Screenshots**
Screenshot 2020-04-06 at 23 13 38

**Are you working on it?**
No

### PR DESCRIPTION
**Pull request by ValanceThomas5**
## Purpose

The purpose of this PR is to fix #56 

## Goals
To improve the quality of the St. Anthony's College logo

### Screenshots
Berfore
92241683_2492852814378175_7836142508424822784_n

After
logo

  
### Preview Link
https://valancethomas5.github.io/sack-site/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by jayasanka-sack** [comment]
@all-contributors please add @ValanceThomas5  for code

**Comment by jayasanka-sack** [comment]
@ValanceThomas5 are you still working on this issue?

**Comment by kumuditha-udayanga** [comment]
Please update your progress on this.

**Comment by jayasanka-sack** [comment]
Closing since no activity.

**Pull request closed without merging**
