### PR TITLE
Change contact number colour in home page

### LINKED ISSUE #325: Change colour of the contact number in the homepage
**Describe the bug**
- The colour of the contact number on the bottom of the home page is purple.

**Expected behaviour**
- Change the colour to #00316A

**Screenshots**
Screenshot 2022-01-11 at 23 25 11

### PR DESCRIPTION
**Pull request by VishwaAmarasinghe**
## Purpose

The purpose of this PR is to fix #325

## Goals

"Change contact number colour in home page"

## Approach

I made some changes in custom.css and index.html to give the color #00316A to the phone number

### Screenshots

image

  
### Preview Link
https://vishwaamarasinghe.github.io/sack-site/
##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by VishwaAmarasinghe** [comment]
Sorry for closing and reopening this one

**Comment by Yoshitha-SACK** [comment]
@VishwaAmarasinghe please provide a preview link

**Comment by Yoshitha-SACK** [comment]
And change the issue number to #325

**Comment by VishwaAmarasinghe** [comment]
Ok thanks for helping

**Review by Piumal1999 — APPROVED** [review]
Well done!! @VishwaAmarasinghe 🤩
Thank you for contributing

**Pull request merged**
